config/routes.rb
Cleverconnect::Application.routes.draw do
  resources :companies
  root :to => redirect('/companies')
  end

app/models/company.rb
class Company < ActiveRecord::Base
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
  def show
    id=params[:id]
    @company = Company.find(id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.haml
-#  This file is app/views/companies/index.html.haml
%h2 All Companies

%table#companies
  %thead
    %tr
      %th Company Name
      %th Price Range
      %th Coverage Area
      %th More Info
  %tbody
    - @companies.each do |company|
      %tr
        %td= company.name 
        %td= company.price_range
        %td= company.coverage_area
        %td= link_to "More about #{company.name}", company_path(company)

app/views/companies/show.html.haml
%h2 Details about #{@company.name}

%ul#details
  %li
    Price Range:
    = @company.price_range
  %li
    Coverage Area:
    = @company.coverage_area

%h3 Description:

%p#description= @company.description

= link_to 'Back to company list', company_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Clever Connect!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = yield